trigger:
- main   # change branch if needed

pool:
  name: 'Default'

steps:
# Step 1: Use Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Set up Python'

# Step 2: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install jobspy pandas
  displayName: 'Install Python packages'

# Step 3: Run job scraper
- script: |
    python job_scraper.py
  displayName: 'Run Job Scraper'

# Step 4: Publish CSV artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'jobs.csv'
    ArtifactName: 'job_results'
    publishLocation: 'Container'
  displayName: 'Publish scraped jobs CSV'
